### ISSUE TITLE
Submit to CRAN?

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nodeSub#10]
Hi @thijsjanzen,

I would enjoy to put pirouette on CRAN as this is mentioned in the accepted (yay!) article about pirouette. 

To be allowed to do so, all the pirouette dependencies must be on CRAN. Do you plan to submit nodeSub to CRAN?

 * If yes: awesome!
 * If no: no worries, I will reluctantly remove the nodeSub dependency from pirouette

Let me know your plans :+1:

**Comment by thijsjanzen** [comment]
Yes, nodeSub will appear on CRAN once the accompanying article is accepted.
Currently, the manuscript is still under review however (1st round).

**Comment by richelbilderbeek** [comment]
Such bad luck my article got accepted first :grin: :+1:

In that case, I will temporarily remove the dependencies, until your work of art is published.

**Comment by thijsjanzen** [comment]
I hope that will be soon too - but that kind of depends on the reviewers and the editor (maybe you can reach out to the editor, it's Luke ;) )
