### ISSUE TITLE
No deprecation message for `sim_dual_linked`

### ISSUE THREAD

**Issue by richelbilderbeek** [thijsjanzen/nodeSub#9]
Hi @thijsjanzen,

My Travis CI build logs fail, such as [this one](https://travis-ci.org/github/richelbilderbeek/pirouette/jobs/727670154#L8914), with the message:

```
'sim_dual_linked' is not an exported object from 'namespace:nodeSub'
```

I would have enjoyed to see a deprecation message to redirect me to the new name. Or a NEWS.md file that shows the changes made. Then, for now, I'd like to know is the new name of this function?

Thanks and cheers, Richel

**Comment by thijsjanzen** [comment]
`sim_linked`

**Comment by richelbilderbeek** [comment]
And `sim_dual_independent`, became `sim_unlinked` :+1:

**Comment by thijsjanzen** [comment]
> And `sim_dual_independent`, became `sim_unlinked` 👍

correct
